### PR TITLE
Ft/navbar fix

### LINKED ISSUE #31: Navbar Issues
When Logo is clicked, it should navigate a user to the `/` page.
A user should also be able to logout if loged in and in the `/` page

### PR DESCRIPTION
**Pull request by kelvinkipruto**
This PR allows a user to logout from the homepage if logged in. It also fixes navigation when logo is clicked.
login

Fixes #31

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
👍🏽 

Sign out button looks off.
Screenshot from 2022-11-28 17-19-02
(I assume we want the blue with white text... Otherwise, all good).

Once logged in, the Toolbar looks broken.
Screenshot from 2022-11-28 17-18-28


Both on Firefox.

**Comment by kelvinkipruto** [comment]
@kilemensi Can't seem to be able to reproduce the navbar issue
nav-ggod

**Comment by kilemensi** [comment]
> @kilemensi Can't seem to be able to reproduce the navbar issue
>

Then ask @thepsalmist to review this PR @kelvinkipruto . Could be local caching issue. Will try clearing everything and try again later.

Few things:

1. There is also this ugly focus on FeeldShield logo/name when page is first loaded. I think we need to remove it (unless it's another one of my local issues).
Screenshot from 2022-11-29 10-16-19
2. After you've logged in and click the FeedShield logo to go back to the landing page:
  i. How do you get back to the "app" page i.e. `/home` I believe.
  ii. What happens to the Start with Twitter button? I mean one is already logged in at this point if I get the description of this PR correct.

**Comment by kelvinkipruto** [comment]
> > @kilemensi Can't seem to be able to reproduce the navbar issue
> 
> Then ask @thepsalmist to review this PR @kelvinkipruto . Could be local caching issue. Will try clearing everything and try again later.
> 
> Few things:
> 
> 1. There is also this ugly focus on FeeldShield logo/name when page is first loaded. I think we need to remove it (unless it's another one of my local issues).
>    Screenshot from 2022-11-29 10-16-19
> 2. After you've logged in and click the FeedShield logo to go back to the landing page:
>    i. How do you get back to the "app" page i.e. `/home` I believe.
>    ii. What happens to the Start with Twitter button? I mean one is already logged in at this point if I get the description of this PR correct.

We never discussed this. I think the best option would be to change the text to something like `Visit Dashboard`, then redirect the user, and not log in again

**Comment by thepsalmist** [comment]
> > @kilemensi Can't seem to be able to reproduce the navbar issue
> 
> Then ask @thepsalmist to review this PR @kelvinkipruto . Could be local caching issue. Will try clearing everything and try again later.
> 
> Few things:
> 
> 1. There is also this ugly focus on FeeldShield logo/name when page is first loaded. I think we need to remove it (unless it's another one of my local issues).
>    Screenshot from 2022-11-29 10-16-19
> 2. After you've logged in and click the FeedShield logo to go back to the landing page:
>    i. How do you get back to the "app" page i.e. `/home` I believe.
>    ii. What happens to the Start with Twitter button? I mean one is already logged in at this point if I get the description of this PR correct.

@kelvinkipruto Can also see the focus on the FeeShield logo on first page load.
@kilemensi The navbar issue looks good to me as per #[79fd38c](https://github.com/CodeForAfrica/harassment-manager/pull/32/commits/79fd38c1c1e7ae69b5c88a57effbc1687055046b)

**Comment by kelvinkipruto** [comment]
@kilemensi @thepsalmist Fixed the outline issue. Please check if you still getting it.

**Comment by kilemensi** [comment]
> @kilemensi @thepsalmist Fixed the outline issue. Please check if you still getting it.

If @thepsalmist has confirmed that it works on his end, don't wait for me on this one @kelvinkipruto but have you raised the https://github.com/CodeForAfrica/harassment-manager/pull/32#issuecomment-1330192384 with the team? Or you guys going to have another back and forth changes?

**Comment by kelvinkipruto** [comment]
@kilemensi They are ok with how I have [updated](https://github.com/CodeForAfrica/harassment-manager/blob/ft/navbar-fix/src/app/welcome-page/welcome-page.component.html#L46) it.

**Comment by kilemensi** [comment]
> @kilemensi They are ok with how I have [updated](https://github.com/CodeForAfrica/harassment-manager/blob/ft/navbar-fix/src/app/welcome-page/welcome-page.component.html#L46) it.

Then go ahead with the deployment @kelvinkipruto

**Pull request merged**
