### PR TITLE
Ft/sentry setup

### PR DESCRIPTION
**Pull request by kelvinkipruto**
Sentry setup implementation

### CODE REVIEW

**Review by kilemensi — COMMENTED** [review]
Sentry setup looks good to go.

---

Why does GitHub says 25,217 additions, 512 deletions on `package-lock.json`? We're only adding one package.

What else is changing & why?

**Comment by kelvinkipruto** [comment]
@kilemensi I think that is common with `package-lock`. It could also be so due to merging changes from upstream

**Review by koechkevin — APPROVED** [review]

**Comment by kilemensi** [comment]
> @kilemensi I think that is common with `package-lock`. It could also be so due to merging changes from upstream

When I asked, there were no merges from upstream @kelvinkipruto. (Even now, I don't see any merge from upstream).

**Comment by kelvinkipruto** [comment]
@kilemensi All unmerged changes from upstream are only in the [`package-lock`](https://github.com/conversationai/harassment-manager/pull/26/files)

**Comment by kilemensi** [comment]
> @kilemensi All unmerged changes from upstream are only in the [`package-lock`](https://github.com/conversationai/harassment-manager/pull/26/files)

If that's the case then I'm not sure what you mean by `upstream` @kelvinkipruto . _I mean [conversationai/harassment-manager](https://github.com/conversationai/harassment-manager) repo_, and there are more than just `package-lock.json` changes.

https://github.com/CodeForAfrica/harassment-manager/compare/main...conversationai:harassment-manager:main

**Comment by kelvinkipruto** [comment]
@kilemensi We had moved most of those changes already. The only one pending was [this](https://github.com/conversationai/harassment-manager/pull/26). If you check this PR's commits, they include those changes as I have merged upstream.

**Comment by kilemensi** [comment]
> main...conversationai:harassment-manager:main

Mr. @kelvinkipruto, the only thing I'd like to see is GitHub telling me we're on par with upstream. Can we do that?

**Comment by kelvinkipruto** [comment]
@kilemensi Yes. Once we merge this PR we will be at par

**Comment by kilemensi** [comment]
Meaning https://github.com/CodeForAfrica/harassment-manager/compare/main...conversationai:harassment-manager:main will say no changes @kelvinkipruto ?

**Comment by kelvinkipruto** [comment]
@kilemensi I think so (99%) sure. We can merge it, and if it doesn't solve then we can do it on a different PR

**Comment by kilemensi** [comment]
> @kilemensi I think so (99%) sure. We can merge it, and if it doesn't solve then we can do it on a different PR

Cool, lets do that... happy to learn something new @kelvinkipruto

**Review by kilemensi — APPROVED** [review]

**Comment by kelvinkipruto** [comment]
@kilemensi It worked as expected

**Comment by kilemensi** [comment]
You didn't tell me about 👇🏽 commit though @kelvinkipruto i.e. what I was asking you to do

**Comment by kelvinkipruto** [comment]
@kilemensi I'm not following. Could you resend the screenshot again?

**Comment by kilemensi** [comment]
My Internet is sh!t @kelvinkipruto ... updated.

**Comment by kelvinkipruto** [comment]
OOh, I should have mentioned it 🙃

**Pull request merged**
